Value is outside of valid range for type java.lang.Integer
Wholesale changes:
java.sql.SQLDataException: Value '2149710640' is outside of valid range for type java.lang.Integer
Code to stop fhirextractor in runner
GetQDataSimple(): new code to get the queue data
Changes to getReferences() to try and make it perform better